# Generated by Django 5.2.13 on 2026-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_student_courses_remove_student_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.CharField(default='system', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], default='N/A', max_length=3),
        ),
    ]
